### ISSUE TITLE
[Task List] Basic Features & Functions

### ISSUE THREAD

**Issue by smora015** [smora015/CS164_Final#2]
- [ ] Implement State Machines to ease the process of menu system
- [x] Post a message feature
- [x] Edit subscriptions feature
